// Polymarket's own event titles are the ONLY source of team names (see
// classifyMarkets() in collect.js/backfill.js -- both parse `home vs. away`
// straight out of event.title) and are inconsistent UPSTREAM: the same
// club shows up under its full legal name, a common English short name,
// with/without "FC", with/without diacritics, depending on whatever
// whoever created that specific market typed. Not a parsing bug -- the raw
// source data itself has ~284 distinct strings for far fewer real clubs.
//
// This is a hand-curated map from every raw variant observed live (via
// `SELECT DISTINCT home_team ... UNION SELECT DISTINCT away_team ...`) to
// one canonical display name. Deliberately conservative: two names are
// only merged here when confirmed to be the exact same club -- e.g. "Inter"
// and "Inter Milan" merge, but "Inter Club d'Escaldes" (a small Andorran
// club) does NOT, despite also containing "Inter". Revisit by re-running
// that query periodically as new competitions/qualifiers introduce new
// raw spellings this table doesn't know about yet.
const TEAM_ALIASES = {
  "AC Sparta Praha": "Sparta Praha",
  "AFC Ajax": "Ajax",
  "Ajax Amsterdam": "Ajax",
  Bournemouth: "AFC Bournemouth",
  "AS Monaco FC": "Monaco",
  Roma: "AS Roma",
  "RSC Anderlecht": "Anderlecht",
  "Arsenal FC": "Arsenal",
  "Aston Villa FC": "Aston Villa",
  Villa: "Aston Villa",
  "Atalanta BC": "Atalanta",
  "Athletic Club": "Athletic Bilbao",
  "Atlético Madrid": "Atletico Madrid",
  "Club Atlético de Madrid": "Atletico Madrid",
  "Young Boys": "BSC Young Boys",
  "BV Borussia 09 Dortmund": "Borussia Dortmund",
  "FC Barcelona": "Barcelona",
  "Bayer 04 Leverkusen": "Bayer Leverkusen",
  "FC Bayern München": "Bayern Munich",
  "Sport Lisboa e Benfica": "Benfica",
  "Beşiktaş JK": "Besiktas",
  "Bodo Glimt": "Bodo/Glimt",
  "FK Bodø/Glimt": "Bodo/Glimt",
  "Bologna FC 1909": "Bologna",
  "Brentford FC": "Brentford",
  Brighton: "Brighton & Hove Albion",
  "Brighton & Hove Albion FC": "Brighton & Hove Albion",
  "Burnley FC": "Burnley",
  "RC Celta de Vigo": "Celta de Vigo",
  "Celtic FC": "Celtic",
  "Chelsea FC": "Chelsea",
  "Club Brugge KV": "Club Brugge",
  "Coventry City FC": "Coventry City",
  "Crvena Zvezda": "Red Star Belgrade",
  "FK Crvena Zvezda": "Red Star Belgrade",
  "FK Crvena zvezda": "Red Star Belgrade",
  "Crystal Palace FC": "Crystal Palace",
  "Derry City FC": "Derry City",
  "GNK Dinamo Zagreb": "Dinamo Zagreb",
  "Dynamo Kiev": "Dynamo Kyiv",
  "FK Dynamo Kyiv": "Dynamo Kyiv",
  Frankfurt: "Eintracht Frankfurt",
  "Everton FC": "Everton",
  "FC Basel 1893": "FC Basel",
  "FC Internazionale Milano": "Inter Milan",
  Inter: "Inter Milan",
  "Qairat FK": "FC Kairat Almaty",
  "FC Kopenhagen": "FC København",
  Midtjylland: "FC Midtjylland",
  Porto: "FC Porto",
  "FC Red Bull Salzburg": "RB Salzburg",
  "FC Twente '65": "FC Twente",
  Twente: "FC Twente",
  Viktoria: "Viktoria Plzeň",
  "Viktoria Plzen": "Viktoria Plzeň",
  Plzen: "Viktoria Plzeň",
  "FK Qarabag": "Qarabag",
  "Qarabağ Ağdam FK": "Qarabag",
  "FK RFS": "RFS",
  Fenerbahçe: "Fenerbahce",
  "Fenerbahçe SK": "Fenerbahce",
  "Ferencvarosi TC": "Ferencvaros",
  "Ferencvárosi TC": "Ferencvaros",
  "Feyenoord Rotterdam": "Feyenoord",
  "Fulham FC": "Fulham",
  "Galatasaray SK": "Galatasaray",
  "Glasgow Rangers": "Rangers",
  "Rangers FC": "Rangers",
  "Heart of Midlothian FC": "Heart of Midlothian",
  Ipswich: "Ipswich Town",
  "Juventus FC": "Juventus",
  "KKS Lech Poznań": "Lech Poznań",
  "Lech Poznan": "Lech Poznań",
  "Kuopion PS": "KuPS",
  "LOSC Lille": "Lille",
  "Lille OSC": "Lille",
  "Larne FC": "Larne",
  "Leeds United FC": "Leeds United",
  Leicester: "Leicester City",
  "Liverpool FC": "Liverpool",
  "PFK Ludogorets 1945 Razgrad": "Ludogorets",
  "Olympique Lyonnais": "Lyon",
  "MH Maccabi Tel Aviv": "Maccabi Tel Aviv",
  "Maccabi TLV": "Maccabi Tel Aviv",
  Malmo: "Malmö FF",
  "Malmo FF": "Malmö FF",
  "Man City": "Manchester City",
  "Manchester City FC": "Manchester City",
  "Man Utd": "Manchester United",
  "Manchester United FC": "Manchester United",
  "SSC Napoli": "Napoli",
  Newcastle: "Newcastle United",
  "Newcastle United FC": "Newcastle United",
  "OGC Nice": "Nice",
  "Nottingham Forest FC": "Nottingham Forest",
  "Olympiakos Piraeus": "Olympiacos",
  "Olympiakós SFP": "Olympiacos",
  "Olympique Marseille": "Olympique de Marseille",
  PSV: "PSV Eindhoven",
  "Páfos FC": "Pafos FC",
  "Panathinaikós AO": "Panathinaikos",
  "Paris Saint Germain": "Paris Saint-Germain",
  "Paris Saint-Germain FC": "Paris Saint-Germain",
  "Real Betis Balompié": "Real Betis",
  "Real Madrid CF": "Real Madrid",
  "SC Braga": "Braga",
  "Sport-Club Freiburg": "SC Freiburg",
  "SK Brann": "Brann",
  "SK Puntigamer Sturm Graz": "Sturm Graz",
  "SK Slavia Praha": "Slavia Praha",
  "Slavia Prague": "Slavia Praha",
  "SK Slovan Bratislava": "Slovan Bratislava",
  "ŠK Slovan Bratislava": "Slovan Bratislava",
  "Shamrock Rovers FC": "Shamrock Rovers",
  Spurs: "Tottenham Hotspur",
  Tottenham: "Tottenham Hotspur",
  "Tottenham Hotspur FC": "Tottenham Hotspur",
  "Stade Brestois 29": "Stade Brestois",
  Stuttgart: "VfB Stuttgart",
  "Sunderland AFC": "Sunderland",
  "The New Saints FC": "The New Saints",
  "RU Saint-Gilloise": "Union Saint-Gilloise",
  "Union St-Gilloise": "Union Saint-Gilloise",
  "Union St. Gilloise": "Union Saint-Gilloise",
  "Union St.-Gilloise": "Union Saint-Gilloise",
  "Villarreal CF": "Villarreal",
  "West Ham": "West Ham United",
  "West Ham United FC": "West Ham United",
  Wolverhampton: "Wolverhampton Wanderers",
  "Wolverhampton Wanderers FC": "Wolverhampton Wanderers",
  Wolves: "Wolverhampton Wanderers",
};

export function canonicalTeamName(rawName) {
  const trimmed = rawName.trim();
  return TEAM_ALIASES[trimmed] ?? trimmed;
}

export { TEAM_ALIASES };
